### ISSUE TITLE
Still active? 

### ISSUE THREAD

**Issue by Nippey** [dchen-8/gallery-dl-server#3]
Hey, 
I started updating the code of the server file, as it didn't fit what i needed. 

I thought i could as well feed it back to community. 
Do you take pull requests to update your project and the docker? 

Then I'd push my code to github in the next weeks or so ...

Br nippey

**Comment by dchen-8** [comment]
Hey there,

This project is not really active. I made it for my needs. 

Feel free to fork it. 

David

**Comment by Nippey** [comment]
Hi David,
> I made it for my needs.

Same here .. 
Lets see how far I'll get before family wants me back :)

I may tag you, if it turned to something useful

Nippey
